apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# Log all requests to deployments
- level: RequestResponse
  verbs: ["create", "update", "delete"]
  resources:
  - group: "apps"
    resources: ["deployments"]
# Log all admission controller decisions
- level: RequestResponse
  verbs: ["create", "update", "delete"]
  resources:
  - group: "admissionregistration.k8s.io"
    resources: ["validatingadmissionpolicies", "validatingadmissionpolicybindings"]
# Log all events
- level: RequestResponse
  verbs: ["create", "update", "delete"]
  resources:
  - group: ""
    resources: ["events"]
# Log metadata for all other requests
- level: Metadata
