// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/flow/v1/flow.proto

package flowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowType int32

const (
	FlowType_FLOW_TYPE_UNSPECIFIED FlowType = 0
	FlowType_FLOW_TYPE_TCP         FlowType = 1
	FlowType_FLOW_TYPE_DNS         FlowType = 2
	FlowType_FLOW_TYPE_HTTP        FlowType = 3
)

// Enum value maps for FlowType.
var (
	FlowType_name = map[int32]string{
		0: "FLOW_TYPE_UNSPECIFIED",
		1: "FLOW_TYPE_TCP",
		2: "FLOW_TYPE_DNS",
		3: "FLOW_TYPE_HTTP",
	}
	FlowType_value = map[string]int32{
		"FLOW_TYPE_UNSPECIFIED": 0,
		"FLOW_TYPE_TCP":         1,
		"FLOW_TYPE_DNS":         2,
		"FLOW_TYPE_HTTP":        3,
	}
)

func (x FlowType) Enum() *FlowType {
	p := new(FlowType)
	*p = x
	return p
}

func (x FlowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_flow_v1_flow_proto_enumTypes[0].Descriptor()
}

func (FlowType) Type() protoreflect.EnumType {
	return &file_api_proto_flow_v1_flow_proto_enumTypes[0]
}

func (x FlowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowType.Descriptor instead.
func (FlowType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

type WorkloadEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadEndpoint) Reset() {
	*x = WorkloadEndpoint{}
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadEndpoint) ProtoMessage() {}

func (x *WorkloadEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadEndpoint.ProtoReflect.Descriptor instead.
func (*WorkloadEndpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadEndpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadEndpoint) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *WorkloadEndpoint) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type NetworkEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkEndpoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NetworkEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type NetworkFlow struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              FlowType               `protobuf:"varint,1,opt,name=type,proto3,enum=flow.v1.FlowType" json:"type,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Src               *WorkloadEndpoint      `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Dst               *NetworkEndpoint       `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BytesSent         uint64                 `protobuf:"varint,6,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     uint64                 `protobuf:"varint,7,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkFlow) Reset() {
	*x = NetworkFlow{}
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFlow) ProtoMessage() {}

func (x *NetworkFlow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFlow.ProtoReflect.Descriptor instead.
func (*NetworkFlow) Descriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkFlow) GetType() FlowType {
	if x != nil {
		return x.Type
	}
	return FlowType_FLOW_TYPE_UNSPECIFIED
}

func (x *NetworkFlow) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *NetworkFlow) GetSrc() *WorkloadEndpoint {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *NetworkFlow) GetDst() *NetworkEndpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *NetworkFlow) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NetworkFlow) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkFlow) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type FlowBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Flows         []*NetworkFlow         `protobuf:"bytes,3,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowBatch) Reset() {
	*x = FlowBatch{}
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowBatch) ProtoMessage() {}

func (x *FlowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowBatch.ProtoReflect.Descriptor instead.
func (*FlowBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{3}
}

func (x *FlowBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FlowBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowBatch) GetFlows() []*NetworkFlow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedFlows int64                  `protobuf:"varint,1,opt,name=accepted_flows,json=acceptedFlows,proto3" json:"accepted_flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_flow_v1_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_api_proto_flow_v1_flow_proto_rawDescGZIP(), []int{4}
}

func (x *PushAck) GetAcceptedFlows() int64 {
	if x != nil {
		return x.AcceptedFlows
	}
	return 0
}

var File_api_proto_flow_v1_flow_proto protoreflect.FileDescriptor

const file_api_proto_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/flow/v1/flow.proto\x12\aflow.v1\"`\n" +
	"\x10WorkloadEndpoint\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\"9\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x80\x03\n" +
	"\vNetworkFlow\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.flow.v1.FlowTypeR\x04type\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x12+\n" +
	"\x03src\x18\x03 \x01(\v2\x19.flow.v1.WorkloadEndpointR\x03src\x12*\n" +
	"\x03dst\x18\x04 \x01(\v2\x18.flow.v1.NetworkEndpointR\x03dst\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".flow.v1.NetworkFlow.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x06 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\a \x01(\x04R\rbytesReceived\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\tFlowBatch\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x05flows\x18\x03 \x03(\v2\x14.flow.v1.NetworkFlowR\x05flows\"0\n" +
	"\aPushAck\x12%\n" +
	"\x0eaccepted_flows\x18\x01 \x01(\x03R\racceptedFlows*_\n" +
	"\bFlowType\x12\x19\n" +
	"\x15FLOW_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFLOW_TYPE_TCP\x10\x01\x12\x11\n" +
	"\rFLOW_TYPE_DNS\x10\x02\x12\x12\n" +
	"\x0eFLOW_TYPE_HTTP\x10\x032A\n" +
	"\n" +
	"FlowIngest\x123\n" +
	"\tPushFlows\x12\x12.flow.v1.FlowBatch\x1a\x10.flow.v1.PushAck(\x01BRZPgithub.com/fairwindsops/insights-plugins/plugins/network-flow/pkg/flow/v1;flowv1b\x06proto3"

var (
	file_api_proto_flow_v1_flow_proto_rawDescOnce sync.Once
	file_api_proto_flow_v1_flow_proto_rawDescData []byte
)

func file_api_proto_flow_v1_flow_proto_rawDescGZIP() []byte {
	file_api_proto_flow_v1_flow_proto_rawDescOnce.Do(func() {
		file_api_proto_flow_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_flow_v1_flow_proto_rawDesc), len(file_api_proto_flow_v1_flow_proto_rawDesc)))
	})
	return file_api_proto_flow_v1_flow_proto_rawDescData
}

var file_api_proto_flow_v1_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_flow_v1_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_flow_v1_flow_proto_goTypes = []any{
	(FlowType)(0),            // 0: flow.v1.FlowType
	(*WorkloadEndpoint)(nil), // 1: flow.v1.WorkloadEndpoint
	(*NetworkEndpoint)(nil),  // 2: flow.v1.NetworkEndpoint
	(*NetworkFlow)(nil),      // 3: flow.v1.NetworkFlow
	(*FlowBatch)(nil),        // 4: flow.v1.FlowBatch
	(*PushAck)(nil),          // 5: flow.v1.PushAck
	nil,                      // 6: flow.v1.NetworkFlow.MetadataEntry
}
var file_api_proto_flow_v1_flow_proto_depIdxs = []int32{
	0, // 0: flow.v1.NetworkFlow.type:type_name -> flow.v1.FlowType
	1, // 1: flow.v1.NetworkFlow.src:type_name -> flow.v1.WorkloadEndpoint
	2, // 2: flow.v1.NetworkFlow.dst:type_name -> flow.v1.NetworkEndpoint
	6, // 3: flow.v1.NetworkFlow.metadata:type_name -> flow.v1.NetworkFlow.MetadataEntry
	3, // 4: flow.v1.FlowBatch.flows:type_name -> flow.v1.NetworkFlow
	4, // 5: flow.v1.FlowIngest.PushFlows:input_type -> flow.v1.FlowBatch
	5, // 6: flow.v1.FlowIngest.PushFlows:output_type -> flow.v1.PushAck
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_flow_v1_flow_proto_init() }
func file_api_proto_flow_v1_flow_proto_init() {
	if File_api_proto_flow_v1_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_flow_v1_flow_proto_rawDesc), len(file_api_proto_flow_v1_flow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_api_proto_flow_v1_flow_proto_depIdxs,
		EnumInfos:         file_api_proto_flow_v1_flow_proto_enumTypes,
		MessageInfos:      file_api_proto_flow_v1_flow_proto_msgTypes,
	}.Build()
	File_api_proto_flow_v1_flow_proto = out.File
	file_api_proto_flow_v1_flow_proto_goTypes = nil
	file_api_proto_flow_v1_flow_proto_depIdxs = nil
}
