// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: api/proto/flow/v1/flow.proto

package flowv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowIngest_PushFlows_FullMethodName = "/flow.v1.FlowIngest/PushFlows"
)

// FlowIngestClient is the client API for FlowIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowIngestClient interface {
	PushFlows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowBatch, PushAck], error)
}

type flowIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowIngestClient(cc grpc.ClientConnInterface) FlowIngestClient {
	return &flowIngestClient{cc}
}

func (c *flowIngestClient) PushFlows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowIngest_ServiceDesc.Streams[0], FlowIngest_PushFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlowBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowIngest_PushFlowsClient = grpc.ClientStreamingClient[FlowBatch, PushAck]

// FlowIngestServer is the server API for FlowIngest service.
// All implementations must embed UnimplementedFlowIngestServer
// for forward compatibility.
type FlowIngestServer interface {
	PushFlows(grpc.ClientStreamingServer[FlowBatch, PushAck]) error
	mustEmbedUnimplementedFlowIngestServer()
}

// UnimplementedFlowIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowIngestServer struct{}

func (UnimplementedFlowIngestServer) PushFlows(grpc.ClientStreamingServer[FlowBatch, PushAck]) error {
	return status.Errorf(codes.Unimplemented, "method PushFlows not implemented")
}
func (UnimplementedFlowIngestServer) mustEmbedUnimplementedFlowIngestServer() {}
func (UnimplementedFlowIngestServer) testEmbeddedByValue()                    {}

// UnsafeFlowIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowIngestServer will
// result in compilation errors.
type UnsafeFlowIngestServer interface {
	mustEmbedUnimplementedFlowIngestServer()
}

func RegisterFlowIngestServer(s grpc.ServiceRegistrar, srv FlowIngestServer) {
	// If the following call pancis, it indicates UnimplementedFlowIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowIngest_ServiceDesc, srv)
}

func _FlowIngest_PushFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlowIngestServer).PushFlows(&grpc.GenericServerStream[FlowBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowIngest_PushFlowsServer = grpc.ClientStreamingServer[FlowBatch, PushAck]

// FlowIngest_ServiceDesc is the grpc.ServiceDesc for FlowIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flow.v1.FlowIngest",
	HandlerType: (*FlowIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushFlows",
			Handler:       _FlowIngest_PushFlows_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/flow/v1/flow.proto",
}
