// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: flow/v1/flow.proto

package flowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowEventKind int32

const (
	FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED FlowEventKind = 0
	FlowEventKind_FLOW_EVENT_KIND_CONNECT     FlowEventKind = 1
	FlowEventKind_FLOW_EVENT_KIND_TRAFFIC     FlowEventKind = 2
)

// Enum value maps for FlowEventKind.
var (
	FlowEventKind_name = map[int32]string{
		0: "FLOW_EVENT_KIND_UNSPECIFIED",
		1: "FLOW_EVENT_KIND_CONNECT",
		2: "FLOW_EVENT_KIND_TRAFFIC",
	}
	FlowEventKind_value = map[string]int32{
		"FLOW_EVENT_KIND_UNSPECIFIED": 0,
		"FLOW_EVENT_KIND_CONNECT":     1,
		"FLOW_EVENT_KIND_TRAFFIC":     2,
	}
)

func (x FlowEventKind) Enum() *FlowEventKind {
	p := new(FlowEventKind)
	*p = x
	return p
}

func (x FlowEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_v1_flow_proto_enumTypes[0].Descriptor()
}

func (FlowEventKind) Type() protoreflect.EnumType {
	return &file_flow_v1_flow_proto_enumTypes[0]
}

func (x FlowEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowEventKind.Descriptor instead.
func (FlowEventKind) EnumDescriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_v1_flow_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_flow_v1_flow_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{1}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_flow_v1_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type WorkloadRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRef) Reset() {
	*x = WorkloadRef{}
	mi := &file_flow_v1_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRef) ProtoMessage() {}

func (x *WorkloadRef) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRef.ProtoReflect.Descriptor instead.
func (*WorkloadRef) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadRef) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *WorkloadRef) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type KubernetesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesRef) Reset() {
	*x = KubernetesRef{}
	mi := &file_flow_v1_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesRef) ProtoMessage() {}

func (x *KubernetesRef) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesRef.ProtoReflect.Descriptor instead.
func (*KubernetesRef) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FlowEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventKind         FlowEventKind          `protobuf:"varint,1,opt,name=event_kind,json=eventKind,proto3,enum=flow.v1.FlowEventKind" json:"event_kind,omitempty"`
	Protocol          Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=flow.v1.Protocol" json:"protocol,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Src               *WorkloadRef           `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	SrcEndpoint       *Endpoint              `protobuf:"bytes,5,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	Dst               *Endpoint              `protobuf:"bytes,6,opt,name=dst,proto3" json:"dst,omitempty"`
	BytesSent         uint64                 `protobuf:"varint,7,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     uint64                 `protobuf:"varint,8,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_flow_v1_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{3}
}

func (x *FlowEvent) GetEventKind() FlowEventKind {
	if x != nil {
		return x.EventKind
	}
	return FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED
}

func (x *FlowEvent) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *FlowEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *FlowEvent) GetSrc() *WorkloadRef {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *FlowEvent) GetSrcEndpoint() *Endpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *FlowEvent) GetDst() *Endpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *FlowEvent) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *FlowEvent) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type FlowEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*FlowEvent           `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEventBatch) Reset() {
	*x = FlowEventBatch{}
	mi := &file_flow_v1_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEventBatch) ProtoMessage() {}

func (x *FlowEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEventBatch.ProtoReflect.Descriptor instead.
func (*FlowEventBatch) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{4}
}

func (x *FlowEventBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FlowEventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowEventBatch) GetEvents() []*FlowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type EnrichedFlowEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeName          string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventKind         FlowEventKind          `protobuf:"varint,3,opt,name=event_kind,json=eventKind,proto3,enum=flow.v1.FlowEventKind" json:"event_kind,omitempty"`
	Protocol          Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=flow.v1.Protocol" json:"protocol,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,5,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Src               *WorkloadRef           `protobuf:"bytes,6,opt,name=src,proto3" json:"src,omitempty"`
	SrcWorkload       *KubernetesRef         `protobuf:"bytes,7,opt,name=src_workload,json=srcWorkload,proto3" json:"src_workload,omitempty"`
	SrcEndpoint       *Endpoint              `protobuf:"bytes,8,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	Dst               *Endpoint              `protobuf:"bytes,9,opt,name=dst,proto3" json:"dst,omitempty"`
	DstRef            *KubernetesRef         `protobuf:"bytes,10,opt,name=dst_ref,json=dstRef,proto3" json:"dst_ref,omitempty"`
	BytesSent         uint64                 `protobuf:"varint,11,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     uint64                 `protobuf:"varint,12,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrichedFlowEvent) Reset() {
	*x = EnrichedFlowEvent{}
	mi := &file_flow_v1_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedFlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedFlowEvent) ProtoMessage() {}

func (x *EnrichedFlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedFlowEvent.ProtoReflect.Descriptor instead.
func (*EnrichedFlowEvent) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{5}
}

func (x *EnrichedFlowEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnrichedFlowEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedFlowEvent) GetEventKind() FlowEventKind {
	if x != nil {
		return x.EventKind
	}
	return FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED
}

func (x *EnrichedFlowEvent) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *EnrichedFlowEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *EnrichedFlowEvent) GetSrc() *WorkloadRef {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *EnrichedFlowEvent) GetSrcWorkload() *KubernetesRef {
	if x != nil {
		return x.SrcWorkload
	}
	return nil
}

func (x *EnrichedFlowEvent) GetSrcEndpoint() *Endpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *EnrichedFlowEvent) GetDst() *Endpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *EnrichedFlowEvent) GetDstRef() *KubernetesRef {
	if x != nil {
		return x.DstRef
	}
	return nil
}

func (x *EnrichedFlowEvent) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *EnrichedFlowEvent) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type EnrichedFlowEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  string                 `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*EnrichedFlowEvent   `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedFlowEventBatch) Reset() {
	*x = EnrichedFlowEventBatch{}
	mi := &file_flow_v1_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedFlowEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedFlowEventBatch) ProtoMessage() {}

func (x *EnrichedFlowEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedFlowEventBatch.ProtoReflect.Descriptor instead.
func (*EnrichedFlowEventBatch) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichedFlowEventBatch) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetEvents() []*EnrichedFlowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PushAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedEvents int64                  `protobuf:"varint,1,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_flow_v1_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_flow_v1_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_flow_v1_flow_proto_rawDescGZIP(), []int{7}
}

func (x *PushAck) GetAcceptedEvents() int64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

var File_flow_v1_flow_proto protoreflect.FileDescriptor

const file_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x12flow/v1/flow.proto\x12\aflow.v1\"2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"[\n" +
	"\vWorkloadRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\"U\n" +
	"\rKubernetesRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xea\x02\n" +
	"\tFlowEvent\x125\n" +
	"\n" +
	"event_kind\x18\x01 \x01(\x0e2\x16.flow.v1.FlowEventKindR\teventKind\x12-\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x11.flow.v1.ProtocolR\bprotocol\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12&\n" +
	"\x03src\x18\x04 \x01(\v2\x14.flow.v1.WorkloadRefR\x03src\x124\n" +
	"\fsrc_endpoint\x18\x05 \x01(\v2\x11.flow.v1.EndpointR\vsrcEndpoint\x12#\n" +
	"\x03dst\x18\x06 \x01(\v2\x11.flow.v1.EndpointR\x03dst\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\a \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\b \x01(\x04R\rbytesReceived\"t\n" +
	"\x0eFlowEventBatch\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12*\n" +
	"\x06events\x18\x03 \x03(\v2\x12.flow.v1.FlowEventR\x06events\"\x96\x04\n" +
	"\x11EnrichedFlowEvent\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x125\n" +
	"\n" +
	"event_kind\x18\x03 \x01(\x0e2\x16.flow.v1.FlowEventKindR\teventKind\x12-\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x11.flow.v1.ProtocolR\bprotocol\x12.\n" +
	"\x13timestamp_unix_nano\x18\x05 \x01(\x03R\x11timestampUnixNano\x12&\n" +
	"\x03src\x18\x06 \x01(\v2\x14.flow.v1.WorkloadRefR\x03src\x129\n" +
	"\fsrc_workload\x18\a \x01(\v2\x16.flow.v1.KubernetesRefR\vsrcWorkload\x124\n" +
	"\fsrc_endpoint\x18\b \x01(\v2\x11.flow.v1.EndpointR\vsrcEndpoint\x12#\n" +
	"\x03dst\x18\t \x01(\v2\x11.flow.v1.EndpointR\x03dst\x12/\n" +
	"\adst_ref\x18\n" +
	" \x01(\v2\x16.flow.v1.KubernetesRefR\x06dstRef\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\v \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\f \x01(\x04R\rbytesReceived\"\xc2\x01\n" +
	"\x16EnrichedFlowEventBatch\x12\"\n" +
	"\forganization\x18\x01 \x01(\tR\forganization\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x122\n" +
	"\x06events\x18\x05 \x03(\v2\x1a.flow.v1.EnrichedFlowEventR\x06events\"2\n" +
	"\aPushAck\x12'\n" +
	"\x0faccepted_events\x18\x01 \x01(\x03R\x0eacceptedEvents*j\n" +
	"\rFlowEventKind\x12\x1f\n" +
	"\x1bFLOW_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FLOW_EVENT_KIND_CONNECT\x10\x01\x12\x1b\n" +
	"\x17FLOW_EVENT_KIND_TRAFFIC\x10\x02*6\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x012\x92\x01\n" +
	"\n" +
	"FlowIngest\x129\n" +
	"\n" +
	"PushEvents\x12\x17.flow.v1.FlowEventBatch\x1a\x10.flow.v1.PushAck(\x01\x12I\n" +
	"\x12PushEnrichedEvents\x12\x1f.flow.v1.EnrichedFlowEventBatch\x1a\x10.flow.v1.PushAck(\x01BRZPgithub.com/fairwindsops/insights-plugins/plugins/network-flow/pkg/flow/v1;flowv1b\x06proto3"

var (
	file_flow_v1_flow_proto_rawDescOnce sync.Once
	file_flow_v1_flow_proto_rawDescData []byte
)

func file_flow_v1_flow_proto_rawDescGZIP() []byte {
	file_flow_v1_flow_proto_rawDescOnce.Do(func() {
		file_flow_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_v1_flow_proto_rawDesc), len(file_flow_v1_flow_proto_rawDesc)))
	})
	return file_flow_v1_flow_proto_rawDescData
}

var file_flow_v1_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flow_v1_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_flow_v1_flow_proto_goTypes = []any{
	(FlowEventKind)(0),             // 0: flow.v1.FlowEventKind
	(Protocol)(0),                  // 1: flow.v1.Protocol
	(*Endpoint)(nil),               // 2: flow.v1.Endpoint
	(*WorkloadRef)(nil),            // 3: flow.v1.WorkloadRef
	(*KubernetesRef)(nil),          // 4: flow.v1.KubernetesRef
	(*FlowEvent)(nil),              // 5: flow.v1.FlowEvent
	(*FlowEventBatch)(nil),         // 6: flow.v1.FlowEventBatch
	(*EnrichedFlowEvent)(nil),      // 7: flow.v1.EnrichedFlowEvent
	(*EnrichedFlowEventBatch)(nil), // 8: flow.v1.EnrichedFlowEventBatch
	(*PushAck)(nil),                // 9: flow.v1.PushAck
}
var file_flow_v1_flow_proto_depIdxs = []int32{
	0,  // 0: flow.v1.FlowEvent.event_kind:type_name -> flow.v1.FlowEventKind
	1,  // 1: flow.v1.FlowEvent.protocol:type_name -> flow.v1.Protocol
	3,  // 2: flow.v1.FlowEvent.src:type_name -> flow.v1.WorkloadRef
	2,  // 3: flow.v1.FlowEvent.src_endpoint:type_name -> flow.v1.Endpoint
	2,  // 4: flow.v1.FlowEvent.dst:type_name -> flow.v1.Endpoint
	5,  // 5: flow.v1.FlowEventBatch.events:type_name -> flow.v1.FlowEvent
	0,  // 6: flow.v1.EnrichedFlowEvent.event_kind:type_name -> flow.v1.FlowEventKind
	1,  // 7: flow.v1.EnrichedFlowEvent.protocol:type_name -> flow.v1.Protocol
	3,  // 8: flow.v1.EnrichedFlowEvent.src:type_name -> flow.v1.WorkloadRef
	4,  // 9: flow.v1.EnrichedFlowEvent.src_workload:type_name -> flow.v1.KubernetesRef
	2,  // 10: flow.v1.EnrichedFlowEvent.src_endpoint:type_name -> flow.v1.Endpoint
	2,  // 11: flow.v1.EnrichedFlowEvent.dst:type_name -> flow.v1.Endpoint
	4,  // 12: flow.v1.EnrichedFlowEvent.dst_ref:type_name -> flow.v1.KubernetesRef
	7,  // 13: flow.v1.EnrichedFlowEventBatch.events:type_name -> flow.v1.EnrichedFlowEvent
	6,  // 14: flow.v1.FlowIngest.PushEvents:input_type -> flow.v1.FlowEventBatch
	8,  // 15: flow.v1.FlowIngest.PushEnrichedEvents:input_type -> flow.v1.EnrichedFlowEventBatch
	9,  // 16: flow.v1.FlowIngest.PushEvents:output_type -> flow.v1.PushAck
	9,  // 17: flow.v1.FlowIngest.PushEnrichedEvents:output_type -> flow.v1.PushAck
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_flow_v1_flow_proto_init() }
func file_flow_v1_flow_proto_init() {
	if File_flow_v1_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_v1_flow_proto_rawDesc), len(file_flow_v1_flow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_flow_v1_flow_proto_depIdxs,
		EnumInfos:         file_flow_v1_flow_proto_enumTypes,
		MessageInfos:      file_flow_v1_flow_proto_msgTypes,
	}.Build()
	File_flow_v1_flow_proto = out.File
	file_flow_v1_flow_proto_goTypes = nil
	file_flow_v1_flow_proto_depIdxs = nil
}
