apiVersion: batch/v1
kind: Job
metadata:
  name: <TESTNAME>
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: <TESTNAME>
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: <TESTNAME>
    spec:
      initContainers:
      - image: <TESTIMAGE>
        imagePullPolicy: Never
        name: <TESTNAME>
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /output
          name: output
      containers:
      - command:
        - sh
        - -c
        - sleep
        - "99999"
        image: alpine:latest
        imagePullPolicy: Always
        name: insights-sleep
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /output
          name: output
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: output