insights:
  organization: ci-co
  cluster: k8test

kubesec:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

kubebench:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

opa:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

rbacreporter:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m
trivy:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m
  namespaceBlacklist:
  - kube-system
  - default
  - insights-agent

uploader:
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

goldilocks:
  enabled: false

polaris:
  enabled: false

pluto:
  enabled: false

nova:
  enabled: false

workloads:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

kubehunter:
  enabled: false

rightsizer:
  enabled: true 
  updateMemoryLimits:
    enabled: true
    minOOMs: 2
    increment: 1.2
    max: 2.0
  extraArgs:
  - "-v4"
