insights:
  organization: ci-co
  cluster: k8test

kube-bench:
  enabled: true
  schedule: "0 0 1 1 0"
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

pluto:
  enabled: true
  schedule: "0 0 1 1 0"
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

rbac-reporter:
  enabled: true
  schedule: "0 0 1 1 0"
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

trivy:
  enabled: true
  schedule: "0 0 1 1 0"
  namespaceBlacklist:
  - kube-system
  - default
  - insights-agent
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

uploader:
  resources:
    requests:
      memory: 16Mi
      cpu: 1m

goldilocks:
  enabled: false

polaris:
  enabled: false

pluto:
  enabled: false

nova:
  enabled: false

workloads:
  schedule: "0 0 1 1 0"
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

kube-hunter:
  enabled: false

right-sizer:
  enabled: true 
  updateMemoryLimits:
    enabled: true
    minOOMs: 2
    increment: 1.2
    max: 2.0
  extraArgs:
  - "-v4"

opa:
  enabled: true
  schedule: "0 0 1 1 0"
  resources:
    requests:
      memory: 64Mi
      cpu: 1m

prometheus-metrics:
  enabled: true
  schedule: "0 0 1 1 0"
  installPrometheusServer: true
  resources:
    requests:
      memory: 64Mi
      cpu: 1m