// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/v1/ingest.proto

package insightsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkFlowIngest_PushEnrichedEvents_FullMethodName = "/api.v1.NetworkFlowIngest/PushEnrichedEvents"
)

// NetworkFlowIngestClient is the client API for NetworkFlowIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkFlowIngestClient interface {
	PushEnrichedEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnrichedFlowEventBatch, PushAck], error)
}

type networkFlowIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkFlowIngestClient(cc grpc.ClientConnInterface) NetworkFlowIngestClient {
	return &networkFlowIngestClient{cc}
}

func (c *networkFlowIngestClient) PushEnrichedEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnrichedFlowEventBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkFlowIngest_ServiceDesc.Streams[0], NetworkFlowIngest_PushEnrichedEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnrichedFlowEventBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkFlowIngest_PushEnrichedEventsClient = grpc.ClientStreamingClient[EnrichedFlowEventBatch, PushAck]

// NetworkFlowIngestServer is the server API for NetworkFlowIngest service.
// All implementations must embed UnimplementedNetworkFlowIngestServer
// for forward compatibility.
type NetworkFlowIngestServer interface {
	PushEnrichedEvents(grpc.ClientStreamingServer[EnrichedFlowEventBatch, PushAck]) error
	mustEmbedUnimplementedNetworkFlowIngestServer()
}

// UnimplementedNetworkFlowIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkFlowIngestServer struct{}

func (UnimplementedNetworkFlowIngestServer) PushEnrichedEvents(grpc.ClientStreamingServer[EnrichedFlowEventBatch, PushAck]) error {
	return status.Error(codes.Unimplemented, "method PushEnrichedEvents not implemented")
}
func (UnimplementedNetworkFlowIngestServer) mustEmbedUnimplementedNetworkFlowIngestServer() {}
func (UnimplementedNetworkFlowIngestServer) testEmbeddedByValue()                           {}

// UnsafeNetworkFlowIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkFlowIngestServer will
// result in compilation errors.
type UnsafeNetworkFlowIngestServer interface {
	mustEmbedUnimplementedNetworkFlowIngestServer()
}

func RegisterNetworkFlowIngestServer(s grpc.ServiceRegistrar, srv NetworkFlowIngestServer) {
	// If the following call panics, it indicates UnimplementedNetworkFlowIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkFlowIngest_ServiceDesc, srv)
}

func _NetworkFlowIngest_PushEnrichedEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkFlowIngestServer).PushEnrichedEvents(&grpc.GenericServerStream[EnrichedFlowEventBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkFlowIngest_PushEnrichedEventsServer = grpc.ClientStreamingServer[EnrichedFlowEventBatch, PushAck]

// NetworkFlowIngest_ServiceDesc is the grpc.ServiceDesc for NetworkFlowIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkFlowIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.NetworkFlowIngest",
	HandlerType: (*NetworkFlowIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushEnrichedEvents",
			Handler:       _NetworkFlowIngest_PushEnrichedEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/ingest.proto",
}
