// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/v1/ingest.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichedFlowEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeName          string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventKind         FlowEventKind          `protobuf:"varint,3,opt,name=event_kind,json=eventKind,proto3,enum=api.v1.FlowEventKind" json:"event_kind,omitempty"`
	Protocol          Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=api.v1.Protocol" json:"protocol,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,5,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Src               *WorkloadRef           `protobuf:"bytes,6,opt,name=src,proto3" json:"src,omitempty"`
	SrcWorkload       *KubernetesRef         `protobuf:"bytes,7,opt,name=src_workload,json=srcWorkload,proto3" json:"src_workload,omitempty"`
	SrcEndpoint       *Endpoint              `protobuf:"bytes,8,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	Dst               *Endpoint              `protobuf:"bytes,9,opt,name=dst,proto3" json:"dst,omitempty"`
	DstRef            *KubernetesRef         `protobuf:"bytes,10,opt,name=dst_ref,json=dstRef,proto3" json:"dst_ref,omitempty"`
	BytesSent         int64                  `protobuf:"varint,11,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     int64                  `protobuf:"varint,12,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	Dns               *DnsDetails            `protobuf:"bytes,13,opt,name=dns,proto3" json:"dns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrichedFlowEvent) Reset() {
	*x = EnrichedFlowEvent{}
	mi := &file_api_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedFlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedFlowEvent) ProtoMessage() {}

func (x *EnrichedFlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedFlowEvent.ProtoReflect.Descriptor instead.
func (*EnrichedFlowEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichedFlowEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnrichedFlowEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedFlowEvent) GetEventKind() FlowEventKind {
	if x != nil {
		return x.EventKind
	}
	return FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED
}

func (x *EnrichedFlowEvent) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *EnrichedFlowEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *EnrichedFlowEvent) GetSrc() *WorkloadRef {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *EnrichedFlowEvent) GetSrcWorkload() *KubernetesRef {
	if x != nil {
		return x.SrcWorkload
	}
	return nil
}

func (x *EnrichedFlowEvent) GetSrcEndpoint() *Endpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *EnrichedFlowEvent) GetDst() *Endpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *EnrichedFlowEvent) GetDstRef() *KubernetesRef {
	if x != nil {
		return x.DstRef
	}
	return nil
}

func (x *EnrichedFlowEvent) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *EnrichedFlowEvent) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *EnrichedFlowEvent) GetDns() *DnsDetails {
	if x != nil {
		return x.Dns
	}
	return nil
}

type EnrichedFlowEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  string                 `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*EnrichedFlowEvent   `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedFlowEventBatch) Reset() {
	*x = EnrichedFlowEventBatch{}
	mi := &file_api_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedFlowEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedFlowEventBatch) ProtoMessage() {}

func (x *EnrichedFlowEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedFlowEventBatch.ProtoReflect.Descriptor instead.
func (*EnrichedFlowEventBatch) Descriptor() ([]byte, []int) {
	return file_api_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichedFlowEventBatch) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrichedFlowEventBatch) GetEvents() []*EnrichedFlowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PushAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedEvents int64                  `protobuf:"varint,1,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_api_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_api_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *PushAck) GetAcceptedEvents() int64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

var File_api_v1_ingest_proto protoreflect.FileDescriptor

const file_api_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/ingest.proto\x12\x06api.v1\x1a\x12api/v1/types.proto\"\xb5\x04\n" +
	"\x11EnrichedFlowEvent\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x124\n" +
	"\n" +
	"event_kind\x18\x03 \x01(\x0e2\x15.api.v1.FlowEventKindR\teventKind\x12,\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x10.api.v1.ProtocolR\bprotocol\x12.\n" +
	"\x13timestamp_unix_nano\x18\x05 \x01(\x03R\x11timestampUnixNano\x12%\n" +
	"\x03src\x18\x06 \x01(\v2\x13.api.v1.WorkloadRefR\x03src\x128\n" +
	"\fsrc_workload\x18\a \x01(\v2\x15.api.v1.KubernetesRefR\vsrcWorkload\x123\n" +
	"\fsrc_endpoint\x18\b \x01(\v2\x10.api.v1.EndpointR\vsrcEndpoint\x12\"\n" +
	"\x03dst\x18\t \x01(\v2\x10.api.v1.EndpointR\x03dst\x12.\n" +
	"\adst_ref\x18\n" +
	" \x01(\v2\x15.api.v1.KubernetesRefR\x06dstRef\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\v \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\f \x01(\x03R\rbytesReceived\x12$\n" +
	"\x03dns\x18\r \x01(\v2\x12.api.v1.DnsDetailsR\x03dns\"\xc1\x01\n" +
	"\x16EnrichedFlowEventBatch\x12\"\n" +
	"\forganization\x18\x01 \x01(\tR\forganization\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x121\n" +
	"\x06events\x18\x05 \x03(\v2\x19.api.v1.EnrichedFlowEventR\x06events\"2\n" +
	"\aPushAck\x12'\n" +
	"\x0faccepted_events\x18\x01 \x01(\x03R\x0eacceptedEvents2\\\n" +
	"\x11NetworkFlowIngest\x12G\n" +
	"\x12PushEnrichedEvents\x12\x1e.api.v1.EnrichedFlowEventBatch\x1a\x0f.api.v1.PushAck(\x01BeZcgithub.com/fairwindsops/insights-plugins/plugins/network-flow-aggregator/pkg/insights/v1;insightsv1b\x06proto3"

var (
	file_api_v1_ingest_proto_rawDescOnce sync.Once
	file_api_v1_ingest_proto_rawDescData []byte
)

func file_api_v1_ingest_proto_rawDescGZIP() []byte {
	file_api_v1_ingest_proto_rawDescOnce.Do(func() {
		file_api_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ingest_proto_rawDesc), len(file_api_v1_ingest_proto_rawDesc)))
	})
	return file_api_v1_ingest_proto_rawDescData
}

var file_api_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_ingest_proto_goTypes = []any{
	(*EnrichedFlowEvent)(nil),      // 0: api.v1.EnrichedFlowEvent
	(*EnrichedFlowEventBatch)(nil), // 1: api.v1.EnrichedFlowEventBatch
	(*PushAck)(nil),                // 2: api.v1.PushAck
	(FlowEventKind)(0),             // 3: api.v1.FlowEventKind
	(Protocol)(0),                  // 4: api.v1.Protocol
	(*WorkloadRef)(nil),            // 5: api.v1.WorkloadRef
	(*KubernetesRef)(nil),          // 6: api.v1.KubernetesRef
	(*Endpoint)(nil),               // 7: api.v1.Endpoint
	(*DnsDetails)(nil),             // 8: api.v1.DnsDetails
}
var file_api_v1_ingest_proto_depIdxs = []int32{
	3,  // 0: api.v1.EnrichedFlowEvent.event_kind:type_name -> api.v1.FlowEventKind
	4,  // 1: api.v1.EnrichedFlowEvent.protocol:type_name -> api.v1.Protocol
	5,  // 2: api.v1.EnrichedFlowEvent.src:type_name -> api.v1.WorkloadRef
	6,  // 3: api.v1.EnrichedFlowEvent.src_workload:type_name -> api.v1.KubernetesRef
	7,  // 4: api.v1.EnrichedFlowEvent.src_endpoint:type_name -> api.v1.Endpoint
	7,  // 5: api.v1.EnrichedFlowEvent.dst:type_name -> api.v1.Endpoint
	6,  // 6: api.v1.EnrichedFlowEvent.dst_ref:type_name -> api.v1.KubernetesRef
	8,  // 7: api.v1.EnrichedFlowEvent.dns:type_name -> api.v1.DnsDetails
	0,  // 8: api.v1.EnrichedFlowEventBatch.events:type_name -> api.v1.EnrichedFlowEvent
	1,  // 9: api.v1.NetworkFlowIngest.PushEnrichedEvents:input_type -> api.v1.EnrichedFlowEventBatch
	2,  // 10: api.v1.NetworkFlowIngest.PushEnrichedEvents:output_type -> api.v1.PushAck
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_ingest_proto_init() }
func file_api_v1_ingest_proto_init() {
	if File_api_v1_ingest_proto != nil {
		return
	}
	file_api_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ingest_proto_rawDesc), len(file_api_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ingest_proto_goTypes,
		DependencyIndexes: file_api_v1_ingest_proto_depIdxs,
		MessageInfos:      file_api_v1_ingest_proto_msgTypes,
	}.Build()
	File_api_v1_ingest_proto = out.File
	file_api_v1_ingest_proto_goTypes = nil
	file_api_v1_ingest_proto_depIdxs = nil
}
