// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/v1/types.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowEventKind int32

const (
	FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED  FlowEventKind = 0
	FlowEventKind_FLOW_EVENT_KIND_CONNECT      FlowEventKind = 1
	FlowEventKind_FLOW_EVENT_KIND_TRAFFIC      FlowEventKind = 2
	FlowEventKind_FLOW_EVENT_KIND_DNS_QUERY    FlowEventKind = 3
	FlowEventKind_FLOW_EVENT_KIND_DNS_RESPONSE FlowEventKind = 4
)

// Enum value maps for FlowEventKind.
var (
	FlowEventKind_name = map[int32]string{
		0: "FLOW_EVENT_KIND_UNSPECIFIED",
		1: "FLOW_EVENT_KIND_CONNECT",
		2: "FLOW_EVENT_KIND_TRAFFIC",
		3: "FLOW_EVENT_KIND_DNS_QUERY",
		4: "FLOW_EVENT_KIND_DNS_RESPONSE",
	}
	FlowEventKind_value = map[string]int32{
		"FLOW_EVENT_KIND_UNSPECIFIED":  0,
		"FLOW_EVENT_KIND_CONNECT":      1,
		"FLOW_EVENT_KIND_TRAFFIC":      2,
		"FLOW_EVENT_KIND_DNS_QUERY":    3,
		"FLOW_EVENT_KIND_DNS_RESPONSE": 4,
	}
)

func (x FlowEventKind) Enum() *FlowEventKind {
	p := new(FlowEventKind)
	*p = x
	return p
}

func (x FlowEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_types_proto_enumTypes[0].Descriptor()
}

func (FlowEventKind) Type() protoreflect.EnumType {
	return &file_api_v1_types_proto_enumTypes[0]
}

func (x FlowEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowEventKind.Descriptor instead.
func (FlowEventKind) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{0}
}

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_DNS         Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_DNS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_DNS":         2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_types_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_v1_types_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{1}
}

type DnsDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qtype         string                 `protobuf:"bytes,2,opt,name=qtype,proto3" json:"qtype,omitempty"`
	Rcode         string                 `protobuf:"bytes,3,opt,name=rcode,proto3" json:"rcode,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	QueryId       int32                  `protobuf:"varint,5,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsDetails) Reset() {
	*x = DnsDetails{}
	mi := &file_api_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsDetails) ProtoMessage() {}

func (x *DnsDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsDetails.ProtoReflect.Descriptor instead.
func (*DnsDetails) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *DnsDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsDetails) GetQtype() string {
	if x != nil {
		return x.Qtype
	}
	return ""
}

func (x *DnsDetails) GetRcode() string {
	if x != nil {
		return x.Rcode
	}
	return ""
}

func (x *DnsDetails) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *DnsDetails) GetQueryId() int32 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Endpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type WorkloadRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRef) Reset() {
	*x = WorkloadRef{}
	mi := &file_api_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRef) ProtoMessage() {}

func (x *WorkloadRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRef.ProtoReflect.Descriptor instead.
func (*WorkloadRef) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadRef) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *WorkloadRef) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type KubernetesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesRef) Reset() {
	*x = KubernetesRef{}
	mi := &file_api_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesRef) ProtoMessage() {}

func (x *KubernetesRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesRef.ProtoReflect.Descriptor instead.
func (*KubernetesRef) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1_types_proto protoreflect.FileDescriptor

const file_api_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/types.proto\x12\x06api.v1\"\x85\x01\n" +
	"\n" +
	"DnsDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05qtype\x18\x02 \x01(\tR\x05qtype\x12\x14\n" +
	"\x05rcode\x18\x03 \x01(\tR\x05rcode\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x19\n" +
	"\bquery_id\x18\x05 \x01(\x05R\aqueryId\"2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"[\n" +
	"\vWorkloadRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\"U\n" +
	"\rKubernetesRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name*\xab\x01\n" +
	"\rFlowEventKind\x12\x1f\n" +
	"\x1bFLOW_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FLOW_EVENT_KIND_CONNECT\x10\x01\x12\x1b\n" +
	"\x17FLOW_EVENT_KIND_TRAFFIC\x10\x02\x12\x1d\n" +
	"\x19FLOW_EVENT_KIND_DNS_QUERY\x10\x03\x12 \n" +
	"\x1cFLOW_EVENT_KIND_DNS_RESPONSE\x10\x04*H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_DNS\x10\x02BeZcgithub.com/fairwindsops/insights-plugins/plugins/network-flow-aggregator/pkg/insights/v1;insightsv1b\x06proto3"

var (
	file_api_v1_types_proto_rawDescOnce sync.Once
	file_api_v1_types_proto_rawDescData []byte
)

func file_api_v1_types_proto_rawDescGZIP() []byte {
	file_api_v1_types_proto_rawDescOnce.Do(func() {
		file_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_types_proto_rawDesc), len(file_api_v1_types_proto_rawDesc)))
	})
	return file_api_v1_types_proto_rawDescData
}

var file_api_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_types_proto_goTypes = []any{
	(FlowEventKind)(0),    // 0: api.v1.FlowEventKind
	(Protocol)(0),         // 1: api.v1.Protocol
	(*DnsDetails)(nil),    // 2: api.v1.DnsDetails
	(*Endpoint)(nil),      // 3: api.v1.Endpoint
	(*WorkloadRef)(nil),   // 4: api.v1.WorkloadRef
	(*KubernetesRef)(nil), // 5: api.v1.KubernetesRef
}
var file_api_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_types_proto_init() }
func file_api_v1_types_proto_init() {
	if File_api_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_types_proto_rawDesc), len(file_api_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_types_proto_goTypes,
		DependencyIndexes: file_api_v1_types_proto_depIdxs,
		EnumInfos:         file_api_v1_types_proto_enumTypes,
		MessageInfos:      file_api_v1_types_proto_msgTypes,
	}.Build()
	File_api_v1_types_proto = out.File
	file_api_v1_types_proto_goTypes = nil
	file_api_v1_types_proto_depIdxs = nil
}
