// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: aggregator/v1/ingest.proto

package aggregv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventKind         FlowEventKind          `protobuf:"varint,1,opt,name=event_kind,json=eventKind,proto3,enum=aggregator.v1.FlowEventKind" json:"event_kind,omitempty"`
	Protocol          Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=aggregator.v1.Protocol" json:"protocol,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Src               *WorkloadRef           `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	SrcEndpoint       *Endpoint              `protobuf:"bytes,5,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	Dst               *Endpoint              `protobuf:"bytes,6,opt,name=dst,proto3" json:"dst,omitempty"`
	BytesSent         uint64                 `protobuf:"varint,7,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     uint64                 `protobuf:"varint,8,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	Dns               *DnsDetails            `protobuf:"bytes,9,opt,name=dns,proto3" json:"dns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_aggregator_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_aggregator_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *FlowEvent) GetEventKind() FlowEventKind {
	if x != nil {
		return x.EventKind
	}
	return FlowEventKind_FLOW_EVENT_KIND_UNSPECIFIED
}

func (x *FlowEvent) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *FlowEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *FlowEvent) GetSrc() *WorkloadRef {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *FlowEvent) GetSrcEndpoint() *Endpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *FlowEvent) GetDst() *Endpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *FlowEvent) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *FlowEvent) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *FlowEvent) GetDns() *DnsDetails {
	if x != nil {
		return x.Dns
	}
	return nil
}

type FlowEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Events        []*FlowEvent           `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEventBatch) Reset() {
	*x = FlowEventBatch{}
	mi := &file_aggregator_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEventBatch) ProtoMessage() {}

func (x *FlowEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEventBatch.ProtoReflect.Descriptor instead.
func (*FlowEventBatch) Descriptor() ([]byte, []int) {
	return file_aggregator_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *FlowEventBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FlowEventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowEventBatch) GetEvents() []*FlowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PushAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedEvents int64                  `protobuf:"varint,1,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_aggregator_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_aggregator_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *PushAck) GetAcceptedEvents() int64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

var File_aggregator_v1_ingest_proto protoreflect.FileDescriptor

const file_aggregator_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1aaggregator/v1/ingest.proto\x12\raggregator.v1\x1a\x19aggregator/v1/types.proto\"\xb5\x03\n" +
	"\tFlowEvent\x12;\n" +
	"\n" +
	"event_kind\x18\x01 \x01(\x0e2\x1c.aggregator.v1.FlowEventKindR\teventKind\x123\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x17.aggregator.v1.ProtocolR\bprotocol\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12,\n" +
	"\x03src\x18\x04 \x01(\v2\x1a.aggregator.v1.WorkloadRefR\x03src\x12:\n" +
	"\fsrc_endpoint\x18\x05 \x01(\v2\x17.aggregator.v1.EndpointR\vsrcEndpoint\x12)\n" +
	"\x03dst\x18\x06 \x01(\v2\x17.aggregator.v1.EndpointR\x03dst\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\a \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\b \x01(\x04R\rbytesReceived\x12+\n" +
	"\x03dns\x18\t \x01(\v2\x19.aggregator.v1.DnsDetailsR\x03dns\"z\n" +
	"\x0eFlowEventBatch\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x120\n" +
	"\x06events\x18\x03 \x03(\v2\x18.aggregator.v1.FlowEventR\x06events\"2\n" +
	"\aPushAck\x12'\n" +
	"\x0faccepted_events\x18\x01 \x01(\x03R\x0eacceptedEvents2T\n" +
	"\vAgentIngest\x12E\n" +
	"\n" +
	"PushEvents\x12\x1d.aggregator.v1.FlowEventBatch\x1a\x16.aggregator.v1.PushAck(\x01BeZcgithub.com/fairwindsops/insights-plugins/plugins/network-flow-aggregator/pkg/aggregator/v1;aggregv1b\x06proto3"

var (
	file_aggregator_v1_ingest_proto_rawDescOnce sync.Once
	file_aggregator_v1_ingest_proto_rawDescData []byte
)

func file_aggregator_v1_ingest_proto_rawDescGZIP() []byte {
	file_aggregator_v1_ingest_proto_rawDescOnce.Do(func() {
		file_aggregator_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregator_v1_ingest_proto_rawDesc), len(file_aggregator_v1_ingest_proto_rawDesc)))
	})
	return file_aggregator_v1_ingest_proto_rawDescData
}

var file_aggregator_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aggregator_v1_ingest_proto_goTypes = []any{
	(*FlowEvent)(nil),      // 0: aggregator.v1.FlowEvent
	(*FlowEventBatch)(nil), // 1: aggregator.v1.FlowEventBatch
	(*PushAck)(nil),        // 2: aggregator.v1.PushAck
	(FlowEventKind)(0),     // 3: aggregator.v1.FlowEventKind
	(Protocol)(0),          // 4: aggregator.v1.Protocol
	(*WorkloadRef)(nil),    // 5: aggregator.v1.WorkloadRef
	(*Endpoint)(nil),       // 6: aggregator.v1.Endpoint
	(*DnsDetails)(nil),     // 7: aggregator.v1.DnsDetails
}
var file_aggregator_v1_ingest_proto_depIdxs = []int32{
	3, // 0: aggregator.v1.FlowEvent.event_kind:type_name -> aggregator.v1.FlowEventKind
	4, // 1: aggregator.v1.FlowEvent.protocol:type_name -> aggregator.v1.Protocol
	5, // 2: aggregator.v1.FlowEvent.src:type_name -> aggregator.v1.WorkloadRef
	6, // 3: aggregator.v1.FlowEvent.src_endpoint:type_name -> aggregator.v1.Endpoint
	6, // 4: aggregator.v1.FlowEvent.dst:type_name -> aggregator.v1.Endpoint
	7, // 5: aggregator.v1.FlowEvent.dns:type_name -> aggregator.v1.DnsDetails
	0, // 6: aggregator.v1.FlowEventBatch.events:type_name -> aggregator.v1.FlowEvent
	1, // 7: aggregator.v1.AgentIngest.PushEvents:input_type -> aggregator.v1.FlowEventBatch
	2, // 8: aggregator.v1.AgentIngest.PushEvents:output_type -> aggregator.v1.PushAck
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_aggregator_v1_ingest_proto_init() }
func file_aggregator_v1_ingest_proto_init() {
	if File_aggregator_v1_ingest_proto != nil {
		return
	}
	file_aggregator_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregator_v1_ingest_proto_rawDesc), len(file_aggregator_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_v1_ingest_proto_goTypes,
		DependencyIndexes: file_aggregator_v1_ingest_proto_depIdxs,
		MessageInfos:      file_aggregator_v1_ingest_proto_msgTypes,
	}.Build()
	File_aggregator_v1_ingest_proto = out.File
	file_aggregator_v1_ingest_proto_goTypes = nil
	file_aggregator_v1_ingest_proto_depIdxs = nil
}
