// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: aggregator/v1/ingest.proto

package aggregv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngest_PushEvents_FullMethodName = "/aggregator.v1.AgentIngest/PushEvents"
)

// AgentIngestClient is the client API for AgentIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentIngestClient interface {
	PushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowEventBatch, PushAck], error)
}

type agentIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestClient(cc grpc.ClientConnInterface) AgentIngestClient {
	return &agentIngestClient{cc}
}

func (c *agentIngestClient) PushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowEventBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngest_ServiceDesc.Streams[0], AgentIngest_PushEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlowEventBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushEventsClient = grpc.ClientStreamingClient[FlowEventBatch, PushAck]

// AgentIngestServer is the server API for AgentIngest service.
// All implementations must embed UnimplementedAgentIngestServer
// for forward compatibility.
type AgentIngestServer interface {
	PushEvents(grpc.ClientStreamingServer[FlowEventBatch, PushAck]) error
	mustEmbedUnimplementedAgentIngestServer()
}

// UnimplementedAgentIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServer struct{}

func (UnimplementedAgentIngestServer) PushEvents(grpc.ClientStreamingServer[FlowEventBatch, PushAck]) error {
	return status.Error(codes.Unimplemented, "method PushEvents not implemented")
}
func (UnimplementedAgentIngestServer) mustEmbedUnimplementedAgentIngestServer() {}
func (UnimplementedAgentIngestServer) testEmbeddedByValue()                     {}

// UnsafeAgentIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServer will
// result in compilation errors.
type UnsafeAgentIngestServer interface {
	mustEmbedUnimplementedAgentIngestServer()
}

func RegisterAgentIngestServer(s grpc.ServiceRegistrar, srv AgentIngestServer) {
	// If the following call panics, it indicates UnimplementedAgentIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngest_ServiceDesc, srv)
}

func _AgentIngest_PushEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServer).PushEvents(&grpc.GenericServerStream[FlowEventBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_PushEventsServer = grpc.ClientStreamingServer[FlowEventBatch, PushAck]

// AgentIngest_ServiceDesc is the grpc.ServiceDesc for AgentIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.v1.AgentIngest",
	HandlerType: (*AgentIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushEvents",
			Handler:       _AgentIngest_PushEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "aggregator/v1/ingest.proto",
}
